variable "name" {
  description = "The name of the lambda function."
  type        = string
}

variable "timeout" {
  description = "Timeout (in seconds) of the lambda function."
  type        = number
  default     = 30
}

variable "memory_size" {
  description = "Amount of memory (in MB) the lambda function can use at runtime."
  type        = number
  default     = 512
}

variable "file_path" {
  description = "Path to the build output folder (/dist or /build folder) of this lambda function, generated by the module bundler."
  type        = string
}

variable "iam_role_policy" {
  description = "The multi-line string of the lambda function's IAM role policy for access to various other AWS resources."
  type        = string
  default     = ""
}

variable "data_table" {
  description = "The list of tables ARN accessed by aws lambda."
  type        = list(string)
}

variable "env_vars" {
  description = "Map of environment variables for this lambda function."
  type        = map(string)
}


